dist: bionic
language: python
python:
  - "3.8"

install:
   - ./gaction check
   - ./gaction download
   - ./gaction split
   - ./gaction compress
   - ./gaction upload
   - ./gaction notify
script:
   - echo oK!

notifications:
  email:
    - github_king_1025@163.com
