#!/usr/bin/env bash

ROOT=$(pwd)
TASK=$ROOT/tasks
CHECK_COMMAND="$TASK/check"
DOWNLOAD_COMMAND="$TASK/download $ROOT"
UPLOAD_COMMAND="$TASK/upload $ROOT"
NOTIFY_COMMAND="$TASK/notify $ROOT"

function app()
{
  if [ $# -le 1 ]; then
    echo "Usage: $0 [check|download|upload|notify|new|add]"
  else
    local argc=$1; shift 
    case "$1" in
      "check") $CHECK_COMMAND;;
      "download") $DOWNLOAD_COMMAND;;
      "upload") $UPLOAD_COMMAND;;
      "notify") $NOTIFY_COMMAND;;
      "new") shift; create_task $*;;
      "add") shift; add_single_task $*;;
      *) echo error command! $1; exit 1;;
    esac
  fi
}

function add_single_task()
{
   if [ $# -eq 2 ]; then
      echo "# $1" | tee    $ROOT/README.md
      echo "---"  | tee -a $ROOT/README.md
      echo $2     | tee -a $ROOT/README.md
      git add $ROOT && git commit -m "$1" && upss -dt push
   fi
}

function create_task()
{
   declare -a list=($*)
   local tmp=$(mktemp -u)
   for((i=0; i < ${#list[@]}; i++)); do
     echo "# NEW_$i"| tee $tmp
     echo "---"  | tee -a $tmp
     echo "${list[i]}" | tee -a $tmp
   done
   if [ -e $tmp ]; then
     mv $tmp $ROOT/README.md
     git add $ROOT && git commit -m "new" && upss -dt push
   fi
}

app $# $*
