#!/usr/bin/env bash

ROOT=$(pwd)
TIME=$(date "+%Y-%m-%d %H:%M:%S")
RESULT="$ROOT/video"
HTML="$ROOT/report.html"
URL_LIST="$ROOT/url.list"
ACTIONS_URL="https://github.com/King-1025/"

function gen_report()
{
 local flag=0
 local msg="执行成功！"
 SUBJECT_TITLE="Gaction执行成功！"
 if [ ! -e $RESULT ]; then
    flag=1
    msg="处理失败！"
    SUBJECT_TITLE="Gaction执行异常！"
 fi

 rm -rf $HTML

cat > $HTML << EOF
 <!DOCTYPE Html>
 <html>
 <head><title>$SUBJECT_TITLE</title>
 <meta charset="utf-8">
 </head>
 <body align="left">
  <div style="border:2px double #333333; padding: 0px 5px 5px 5px;" >
    <p style="font-size: 16px;">$msg&nbsp;$TIME&nbsp;
    <a style="font-size: 8px; text-decoration: none;" href="$ACTIONS_URL">《查看详情》</a>
    </p>
    <pre style="white-space: pre-wrap;word-wrap: break-word; padding: 10px 10px 10px 10px; border: 2px solid #888; font-size:10px; color: #FFF; background-color: #000;">URL List:
$(if [ -e $URL_LIST ]; then cat $URL_LIST; else echo "Not found URL_LIST: $URL_LIST"; fi)

Result:
$(if [ $flag -eq 0 ]; then ls -lh $RESULT; else echo "Not found directory: $RESULT"; fi)</pre>
  </div>
</body>
</html>
EOF
}

function mail()
{
  if [ -e $HTML ]; then
   if [ ! -z $MAIL_KEY ]; then
     local exe="$ROOT/tools/sendEmail"
     local opt=$(echo $MAIL_KEY | awk -F "/" '{print "-xu "$1" -xp "$2" -f "$1" -s "$3" -t "$4}')
           opt="$opt -o message-content-type=html"
           opt="$opt -o message-charset=utf-8"
           opt="$opt -o message-file=$HTML"
           opt="$opt -o tls=no"
           opt="$opt -u $SUBJECT_TITLE"
     local comm="$exe $opt"
     #echo $comm &&
     $comm
    # if [ $? -eq 0 ]; then
    #    echo notify success!
    # else
#	echo notify failed!
#     fi
   else	
     echo Not found MAIL_KEY!
     exit 1
   fi
  else
     echo Not found report: $HTML
     exit 1
  fi
}

gen_report
mail
