#!/usr/bin/env bash

ROOT=$(pwd)
TIME=$(date "+%Y-%m-%d %H:%M:%S")
RESULT="$ROOT/video"
HTML="$ROOT/report.html"
URL_LIST="$ROOT/url.list"
ACTIONS_URL="https://github.com/King-1025/Gaction/actions"

function gen_report()
{
 local flag=0
 local msg="执行成功！"
 SUBJECT_TITLE="Gaction执行成功！"
 if [ ! -e $RESULT ]; then
    flag=1
    msg="处理失败！"
    SUBJECT_TITLE="Gaction执行异常！"
 fi
 rm -rf $HTML
cat > $HTML << EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>$SUBJECT_TITLE</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
 <style>
 div{border:5px solid #333333; padding: 0px 10px 10px 10px;} 
 pre{padding: 10px 10px 10px 10px; border: 2px solid #888; font-size:20px; color: #FFF; background-color: #000;}
 a{font-size: 20px; text-decoration: none; }
 </style>
    </head>
    <body style="margin-top:0px;margin-bottom:0px;margin-left:0px;margin-right:0px; padding-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">
                <tr><td>

    <h2>$msg&nbsp;$TIME&nbsp;
    <a href="$ACTIONS_URL">《查看详情》</a>
    </h2>
		</td></tr>
                <tr><td>

    <pre>URL List:
$(if [ -e $URL_LIST ]; then cat $URL_LIST; else echo "Not found URL_LIST: $URL_LIST"; fi)

Result:
$(if [ $flag -eq 0 ]; then ls -lh $RESULT; else echo "Not found directory: $RESULT"; fi)</pre>

		</td></tr>
        </table>
    </table>
</body>
</html>
EOF
}

function mail()
{
  if [ -e $HTML ]; then
   if [ ! -z $MAIL_KEY ]; then
     local exe="$ROOT/tools/sendEmail"
     local opt=$(echo $MAIL_KEY | awk -F "/" '{print "-xu "$1" -xp "$2" -f "$1" -s "$3" -t "$4}')
           opt="$opt -o message-content-type=html"
           opt="$opt -o message-charset=utf-8"
           opt="$opt -o message-file=$HTML"
           opt="$opt -o tls=no"
           opt="$opt -u $SUBJECT_TITLE"
     local comm="$exe $opt"
     #echo $comm &&
     $comm
    # if [ $? -eq 0 ]; then
    #    echo notify success!
    # else
#	echo notify failed!
#     fi
   else	
     echo Not found MAIL_KEY!
     exit 1
   fi
  else
     echo Not found report: $HTML
     exit 1
  fi
}

gen_report
mail
