#!/usr/bin/env bash

#echo pass!
#exit 0

ROOT=$(pwd)
INPUT="$ROOT/video"

if [ ! -e $INPUT ]; then
   echo $INPUT not exist!
   exit 1
fi

function esc()
{
   if [ ! -z $ESC_KEY ]; then
     local exe="$ROOT/tools/esc"
     local skey="$(echo $ESC_KEY | awk -F "/" '{print $1" "$2}')"
     local comm="$exe $INPUT $skey"
     echo $comm && $comm
  else
     echo Not found ESC_KEY!
     exit 1
  fi
#   for i in $(find $INPUT -type f -print); do
#      echo "$i upload..."
#      local comm="$exe $INPUT $(basename $i)"
#      echo $comm && $comm
#   done

}

function baidu()
{
  if [ ! -z $BAIDU_KEY ]; then
   local exe="$ROOT/tools/bdwp/BaiduPCS-Go"
   local config="$ROOT/tools/bdwp/config"
   local path="/apps/baidu_shurufa/youtube"
   local comm="$exe login -bduss=$BAIDU_KEY"

   export BAIDUPCS_GO_CONFIG_DIR=$config

   echo $comm && $comm

   comm="$exe upload $INPUT/* $path"

   echo $comm && $comm
 else
   echo Not found BAIDU_KEY!
   exit 1 
 fi
}

esc
#baidu
