#!/usr/bin/env bash

if [ -e "$1" ]; then
  ROOT="$1"
else
  ROOT=$(pwd) 
fi

TOOLS=$ROOT/tools
README=$ROOT/README.md
URL_LIST=$ROOT/url.list
OUTPUT_DIR=$ROOT/video
#YOU_GET_OPTION=
#YOUTUBE_DL_OPTION="-f worstvideo+bestaudio" #--merge-output-format mp4"
#YOUTUBE_DL_OPTION="--merge-output-format mp4"
FMT="%(id)s.%(ext)s"

function setup()
{
   rm -rf $URL_LIST
   while read line; do
     echo $line | grep -qvE "^[#|=|-]"
     if [ $? -eq 0 ] && [ "$line" != "" ]; then
        echo $line | tee -a $URL_LIST
     fi
     echo $line | grep -qE "^#.*:"
     if [ $? -eq 0 ] && [ "$line" != "" ]; then
        FMT=$(echo $line | awk -F ":" '{print $2}')"_$FMT"
     fi
   done < $README
   echo FMT:$FMT
}

function use()
{
  local comm=""
  if [ $# -ge 1 ]; then
     local tag=$1

     if [ "$tag" = "you-get" ]; then
       comm="$TOOLS/you-get/you-get -I $URL_LIST -o $OUTPUT_DIR -a $YOU_GET_OPTION"
     fi

     if [ "$tag" = "youtube-dl" ]; then
       comm="$TOOLS/youtube-dl -a $URL_LIST -o $OUTPUT_DIR/$FMT $YOUTUBE_DL_OPTION"
     fi
  fi
  if [ "$comm" != "" ]; then
     echo $comm && $comm
  else
     echo no command!
  fi
}

#setup
setup && use youtube-dl
