#!/usr/bin/env bash

ROOT=$(pwd)
STORAGE=$ROOT/stage/storage

function app()
{
   local key=$($STORAGE get GITHUB_KEY)
   if [ "$key" != "" ]; then
      auto_push $(echo $key | awk -F "/" '{print $1" "$2}')
   else
      echo "not found GITHUB_KEY!" 
      exit 1
   fi
}

function auto_push()
{
   if [ $# -eq 2 ]; then
    local username=$1
    local password=$2
    local tmp=$(mktemp -u)
    echo "set timeout 120"      >> $tmp
    echo "spawn git push"       >> $tmp
    echo "expect Username"      >> $tmp
    echo "send \"$username\r\"" >> $tmp
    echo "expect Password"      >> $tmp
    echo "send \"$password\r\"" >> $tmp
    echo "expect off"           >> $tmp
    expect -f $tmp
    rm -rf $tmp
    git status
   else
    echo "auto_push only needs 2 arguments!"
    exit 1
  fi
}

app $* $#
